#ifndef NET_EG_DEFINE_H
#define NET_EG_DEFINE_H

typedef enum{
  NET_WIFI_CONNECTED = 0,
  NET_WIFI_DISCONNECT,
  NET_ETH_CONNECTED,
  NET_ETH_DISCONNECT,
  NET_MQTT_SUBSCRIBED,
  NET_MQTT_UNSUBSCRIBED,
  NET_MQTT_PUBLISHED,
  NET_MQTT_ERROR,
  NET_EG_BIT_MAX,
}e_net_eg_bit;


#endif // NET_EG_DEFINE_H
