#ifndef NET_EG_DEFINE_H
#define NET_EG_DEFINE_H

typedef enum{
  NET_WIFI_IS_CONNECTED = 0,
  NET_ETH_IS_CONNECTED,
  NET_MQTT_IS_SUBSCRIBED,
  NET_MQTT_PUBLISHED,
  NET_MQTT_ERROR,
  NET_EG_BIT_MAX,
}e_net_eg_bit;

#define NET_EG_BIT_GET_VALUE(_BIT_) (1UL << (_BIT_))

#endif // NET_EG_DEFINE_H
