name: Coordinator workflow

on:
  workflow_dispatch:
   inputs:
      workflow_type:
        description: 'Select workflow to run'
        required: true
        type: choice
        default: main
        options:
          - main
          - unit_test
          - stub
          - experiment_debug
      unit_test_project:
        description: 'Select unit-test project to run'
        default: unit-test_gd20_inverter_lora_gateway
        type: choice
        options:
          - unit-test_gd20_inverter_lora_gateway
          - unit-test_gd20_inverter_lora_node
          - unit-test_mqtts_cloud_vps_broker
          - unit-test_rtc_ds3231
          - unit-test_ethernet-w5500
          - unit-test_usb_cdc
            

        
jobs:
  call_experiment_debug:
    uses: kori-thespirit/LoraGatewayDevelopment/.github/workflows/experiment_debug_workflow.yml@SCRUM-87-Design-Github-Workflow
    with:
      unit_test_project: ${{ github.event.inputs.unit_test_project }}
