name: Coordinator workflow

on:
  push:
    branches: 'SCRUM-87-Design-Github-Workflow'
  workflow_dispatch:
   inputs:
      workflow_type:
        description: 'Select workflow to run'
        required: true
        type: choice
        default: main
        options:
          - main
          - unit-test
          - stub
          - experiment_debug
      unit_test_project:
        description: 'Select unit-test project to run'
        default: WiFi
        type: choice
        options:
          - RTC-DS3231
          - Inverter_GD20
          - WiFi
          - Ethernet
          - MQTTS
          - Lora
          - USB-CDC

        
jobs:
  call_experiment_debug_workflow:
    if: ${{ github.event.inputs.workflow_type == 'experiment_debug' }}
    uses: kori-thespirit/LoraGatewayDevelopment/.github/workflows/experiment_debug_workflow.yml@SCRUM-87-Design-Github-Workflow
    with:
      unit_test_project: ${{ github.event.inputs.unit_test_project }}
