name: Coordinator workflow

on:
  workflow_dispatch:
    inputs:
      workflow_type:
        description: 'Select workflow to run'
        required: true
        type: choice
        default: main
        options:
          - main
          - unit-test
          - stub
          - experiment_debug
      unit_test_project:
        description: 'Select unit-test project to run'
        default: WiFi
        type: choice
        options:
          - RTC-DS3231
          - Inverter_GD20
          - WiFi
          - Ethernet
          - MQTTS
          - Lora
          - USB-CDC


jobs:
  call_main_workflow:
    runs-on: self-hosted
    if: ${{ github.event.inputs.workflow_type == 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dispatch
        run: echo "Dispatch to main workflow"
  call_experiment_debug_workflow:
    runs-on: self-hosted
    if: ${{ github.event.inputs.workflow_type == 'experiment_debug' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dispatch
        uses: ./.github/workflows/experiment_debug_workflow.yml
