name: Experiment and Debug workflow

on:
  workflow_call:
    inputs:
      experiment_debug_string:
        type: string

jobs:
  experiment:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          experiment_debug_string: ${{ github.event.inputs.experiment_debug_string }}
      - name: experiment
        shell: bash
        run: |
          echo "Print the passed argument: ${{ github.event.inputs.experiment_debug_string }}"
