name: Experiment and Debug workflow

on:
  workflow_call:
    inputs:
      unit_test_project:
        type: string

jobs:
  experiment:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          unit_test_project: ${{ github.event.inputs.unit_test_project }}
      - name: experiment
        run: |
          echo " ${{ github.event.inputs.unit_test_project }} "
          echo "Using project unit-test ${{ github.event.inputs.unit_test_project }}"
