name: Lora gateway USB-CDC Hardware-In-Loop Test

on:
  push:

jobs:
  Flash-Gateway-Firmware:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build flash
        run: |
          . /mnt/hdd_WD10JPVT_1TB/p256GB/share-resource/.espressif/tools/activate_idf_v5.5.4.sh
          cd tools/usb_cdc/esp32s3/

          $IDF_PATH/tools/idf.py set-target esp32s3
          $IDF_PATH/tools/idf.py -p /dev/ttyACM0 build flash

  Python-test:
    runs-on: self-hosted
    steps:
      - name: Wait for boot
        run: sleep 3
        
      - name: Run pytest
        run: |
          . /mnt/hdd_WD10JPVT_1TB/p256GB/share-resource/.espressif/tools/activate_idf_v5.5.4.sh
          pip install -r tools/usb_cdc/python/requirements.txt
          pytest tools/usb_cdc/python/usb-cdc_pytest.py -m usj_device -s -v
