name: ESP32 Hardware-In-Loop Test

on:
  push:

jobs:
  test-on-hardware:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build flash monitor
        run: |
          . /mnt/hdd_WD10JPVT_1TB/p256GB/share-resource/.espressif/tools/activate_idf_v5.5.4.sh
          $IDF_PATH/tools/idf.py set-target esp32s3
          $IDF_PATH/tools/idf.py -p /dev/ttyACM0 build flash monitor

      - name: Wait for boot
        run: sleep 3
        
      - name: Run pytest
        run: pytest -v -s test_v2.py
