name: ESP-IDF CI

on:
  push:
    branches: [ "SPI_Unit_Test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3
          target: esp32c3
          command: |
            idf.py fullclean
            idf.py set-target esp32c3
            idf.py build
