name: Lora gateway USB-CDC stub Hardware-In-Loop Test

on:
  workflow_call:
    inputs:
      unit_test_project:
        required: true
        type: choice

jobs:
  Load_MCU_firmware:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build flash
        run: |
          . /mnt/hdd_WD10JPVT_1TB/p256GB/share-resource/.espressif/tools/activate_idf_v5.5.4.sh
          cd tools/usb_cdc/esp32s3/

          $IDF_PATH/tools/idf.py set-target esp32s3
          $IDF_PATH/tools/idf.py -p /dev/ttyACM0 build flash

  Python_test:
    runs-on: self-hosted
    needs: Load_MCU_firmware
    if: |
      # always() &&
      needs.Load_MCU_firmware.result == 'success'
    steps:
      - name: Wait for boot
        run: sleep 3
      - name: Run pytest
        run: |
          . /mnt/hdd_WD10JPVT_1TB/p256GB/share-resource/.espressif/tools/activate_idf_v5.5.4.sh
          pip install -r tools/usb_cdc/python/requirements.txt
          pytest tools/usb_cdc/python/usb-cdc_pytest.py -m usb_device -s -v -p no:warnings
