name: Lora gateway Unit Test Hardware-In-Loop

on:
  workflow_call:
    inputs:
      unit_test_project:
        required: true
        type: string

jobs:
  Load_MCU_firmware:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          unit_test_project: ${{ github.event.inputs.unit_test_project }}

      - name: build and flash
        run: |
          if [[ "${{ github.event.inputs.unit_test_project }}" == "unit-test_mqtts_cloud_vps_broker" ]]; then
          else
            PROJECT_PATH="${{ vars.UNIT_TEST_PATH }}/${{ github.event.inputs.unit_test_project }}"
            . /mnt/hdd_WD10JPVT_1TB/p256GB/share-resource/.espressif/tools/activate_idf_v5.5.4.sh
            cd $PROJECT_PATH
            $IDF_PATH/tools/idf.py set-target esp32s3
            $IDF_PATH/tools/idf.py -p ${{ vars.UNIX_USB_PORT_0 }} build flash
          fi

  Log_Capture:
    needs: Load_MCU_firmware
    # always() &&
    if: |
      needs.Load_MCU_firmware.result == 'success'
    runs-on: self-hosted
    steps:
      - name: Run log capturer
        run: |
          . /mnt/hdd_WD10JPVT_1TB/p256GB/share-resource/.espressif/tools/activate_idf_v5.5.4.sh
          ls tools/cicd/
          pip install -r tools/cicd/requirements.txt
          python tools/cicd/log_capturer.py
