name: Lora gateway Unit Test Hardware-In-Loop

on:
  workflow_call:
    inputs:
      unit_test_project:
        required: true
        type: string

jobs:
  Load_GD20_inverter_firmware:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build and flash
        run: |
          . /mnt/hdd_WD10JPVT_1TB/p256GB/share-resource/.espressif/tools/activate_idf_v5.5.4.sh
          cd code/unit-test/unit-test_gd20_inverter_lora_gateway/
          $IDF_PATH/tools/idf.py set-target esp32s3
          $IDF_PATH/tools/idf.py -p /dev/ttyACM0 build flash

  Log_Capture:
    needs: Load_GD20_inverter_firmware
    if: |
      # always() &&
      needs.Load_GD20_inverter_firmware.result == 'success'
    runs-on: self-hosted
    steps:
      - name: Run log capturer
        run: |
          . /mnt/hdd_WD10JPVT_1TB/p256GB/share-resource/.espressif/tools/activate_idf_v5.5.4.sh
          ls tools/cicd/
          pip install -r tools/cicd/requirements.txt
          python tools/cicd/log_capturer.py
